### ISSUE TITLE
Git config issue

### ISSUE THREAD

**Issue by mert-kurttutan** [Da1sypetals/Symars#1]
In case you are not already aware, the commits are not associated with your GitHub account.
You might want to git config using the email associated with your GitHub account. Then, the commits will count towards your GitHub account (if you care :))

**Comment by Da1sypetals** [comment]
Thanks a lot! I have not noticed that ❤️ 

Your issue has made me notice a legacy issue of .gitconfig file on my computer. I have backed up the git history in another remote and got to fix this. ❤️
